# Generated by Django 6.0.3 on 2026-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_taskattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
