# Generated by Django 6.0.3 on 2026-03-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="disabled_statuses",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
