# Generated by Django 6.0.3 on 2026-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=10,
            ),
        ),
    ]
